name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Deploy to PythonAnywhere
        env:
          PA_USERNAME: ${{ secrets.PA_USERNAME }}
          PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
          PA_DOMAIN_NAME: ${{ secrets.PA_DOMAIN_NAME }}
          PA_VIRTUAL_ENV: ${{ secrets.PA_VIRTUAL_ENV }}
          PA_PROJECT_DIR: ${{ secrets.PA_PROJECT_DIR }}
        run: |
          # Debugging paths
          curl -X POST "https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/consoles/" \
            -H "Authorization: Token $PA_API_TOKEN" \
            --form executable=python3 \
            --form command="cd $PA_PROJECT_DIR && ls -la && git log -1"

          # Pull latest code and install dependencies
          curl -X POST "https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/tasks/" \
            -H "Authorization: Token $PA_API_TOKEN" \
            --form command="cd $PA_PROJECT_DIR && git fetch origin main && git reset --hard origin/main && source $PA_VIRTUAL_ENV/bin/activate && pip install -r requirements.txt"

          # Run migrations
          curl -X POST "https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/tasks/" \
            -H "Authorization: Token $PA_API_TOKEN" \
            --form command="source $PA_VIRTUAL_ENV/bin/activate && python $PA_PROJECT_DIR/manage.py migrate"

          # Reload the web app
          curl -X POST "https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/webapps/$PA_DOMAIN_NAME/reload/" \
            -H "Authorization: Token $PA_API_TOKEN"
